# Clippy configuration (sane defaults for a skeleton)
# Note: enable Clippy lints via CLI (e.g., `cargo clippy -- -W clippy::pedantic`)
# or configure in Cargo.toml under [workspace.lints.clippy] if supported by your toolchain.
allow-private-module-inception = true
