---
blank_issues_enabled: false
contact_links:
  - name: Security reporting
    url: https://github.com/${{ github.repository }}/security/policy
    about: Please refer to SECURITY.md for vulnerability reporting.
