[package]
name = "xtask"
version = "0.0.1"
edition = "2021"
license = "UNLICENSED"
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
