name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check changelog updated
        shell: bash
        run: |
          set -euo pipefail
          
          # Skip for documentation-only changes
          if git diff --name-only origin/main..HEAD | grep -E '\.(md|txt|yml|yaml)$' | grep -v CHANGELOG.md | wc -l | grep -q '^0$'; then
            echo "Documentation-only change, skipping changelog check"
            exit 0
          fi
          
          # Check if CHANGELOG.md was modified
          if git diff --name-only origin/main..HEAD | grep -q CHANGELOG.md; then
            echo "✅ CHANGELOG.md updated"
          else
            echo "❌ CHANGELOG.md not updated"
            echo "Please add an entry to CHANGELOG.md describing your changes"
            echo "You can add it under the [Unreleased] section"
            exit 1
          fi