name = "dynaps"
vendor = "iniLabs"
family = "DYNAPs"
version = "1"
notes = "Expanded target descriptor."

[capabilities]
on_chip_learning = true
weight_precisions = [8]
max_neurons_per_core = 256
max_synapses_per_core = 16384
time_resolution_ns = 5000

# Expanded capabilities
supports_sparse = true
neuron_models = ["LIF"]
max_fan_in = 256
max_fan_out = 256
core_memory_kib = 64
interconnect_bandwidth_mbps = 200
analog = true
on_chip_plasticity_rules = ["STDP"]
