name = "spinnaker2"
vendor = "Manchester"
family = "SpiNNaker"
version = "2"
notes = "Expanded target descriptor."

[capabilities]
on_chip_learning = false
weight_precisions = [16]
max_neurons_per_core = 1024
max_synapses_per_core = 65536
time_resolution_ns = 1000000

# Expanded capabilities
supports_sparse = true
neuron_models = ["LIF", "Izhikevich"]
max_fan_in = 16384
max_fan_out = 16384
core_memory_kib = 512
interconnect_bandwidth_mbps = 2500
analog = false
on_chip_plasticity_rules = []

# Modeling hints
neuron_mem_kib_per = 0.015
syn_mem_kib_per = 0.003
bytes_per_event = 4
default_spike_rate_hz = 100.0
